#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

[ -f "$XDG_CONFIG_HOME/X11/Xresources" ] && xrdb -merge "$XDG_CONFIG_HOME/X11/Xresources" # Merge resources
[ -f "$XDG_DATA_HOME/bg" ] && setbg "$XDG_DATA_HOME/bg" # Set wallpaper

export SUDO_ASKPASS=ssh-askpass
export SSH_ASKPASS=ssh-askpass

# Kbd set up
xkbdsetup

# Fix screen tearing and set up monitors
xrandr --output HDMI-A-0 --set TearFree on
xrandr --output DisplayPort-0 --right-of HDMI-A-0 --set TearFree on

xset s 900                                  # Lock after 15m inactive

statusbar &
xcompmgr -c -C -t-5 -l-5 -r4.2 -o.55 &      # Compositor
xsidle.sh slock &                           # Lock screen
unclutter &                                 # Unclutter mouse
sxhkd &                                     # Universal bindings
dunst &                                     # Notifications
networkd-notify &                           # Network notifications
lxqt-policykit-agent &                      # Policy Agent

exec $HOME/.local/bin/startdwm              # exec dwm
